"""Add balance column to donors

Revision ID: 725a20faa306
Revises: ea5d25344f12
Create Date: 2025-05-29 07:50:28.944048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725a20faa306'
down_revision: Union[str, None] = 'ea5d25344f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'balance')
    # ### end Alembic commands ###
